name: Deploy to GitHub Pages

on:
  # Déclenchement du workflow lors des push sur la branche `main`
  push:
    branches: [ main ]
  # Permet l'exécution manuelle du workflow via l'onglet Actions sur GitHub
  workflow_dispatch:

# Définition des permissions nécessaires pour le workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Version de Node.js

      # Étape pour mettre en cache les modules pnpm avec actions/cache@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3  # Mise à jour vers v3
        with:
          path: ~/.pnpm-store  # Cache utilisé par pnpm pour stocker les dépendances
          key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}  # Clé de cache basée sur le fichier pnpm-lock.yaml
          restore-keys: |
            node-cache-${{ runner.os }}-pnpm-  # Restauration partielle si aucune clé exacte n'est trouvée

      - name: Install pnpm
        run: npm install -g pnpm  # Installation globale de pnpm

      - name: Display Node.js version
        run: node -v  # Vérification de la version de Node.js

      - name: Display pnpm version
        run: pnpm -v  # Vérification de la version de pnpm

      - name: List files in the repository
        run: ls -alh  # Afficher les fichiers du dépôt pour déboguer

      - name: Install dependencies
        run: pnpm install  # Installation des dépendances avec pnpm

      - name: Build the project
        run: pnpm build  # Construction du projet avec pnpm

  deploy:
    needs: build  # Dépendance de l'étape de build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL de la page déployée
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Action de déploiement sur GitHub Pages
